[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 3

[env]
PYTHON_VERSION = "3.9" 