[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y python3-distutils && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 3

[env]
PYTHON_VERSION = "3.9" 