[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "npm run build"
watchPatterns = ["**/*"]
startCommand = "./start.sh"
restartPolicy = "on-failure"
maxRetries = 5

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 60
healthcheckInterval = 15
startupTime = 90
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[env]
PYTHON_VERSION = "3.9"
PORT = "3000"
API_PORT = "8000"
HOST = "0.0.0.0"
DATABASE_URL = "${DATABASE_URL}"
POSTGRES_USER = "${POSTGRES_USER}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
POSTGRES_DB = "${POSTGRES_DB}"
POSTGRES_HOST = "${POSTGRES_HOST}"
POSTGRES_PORT = "${POSTGRES_PORT}"
DEBUG = "false"
REDIS_URL = "${REDIS_URL}"
ACOUSTID_API_KEY = "${ACOUSTID_API_KEY}"
AUDD_API_KEY = "${AUDD_API_KEY}"
SECRET_KEY = "${SECRET_KEY}"
MUSICBRAINZ_APP_NAME = "sodav-monitor"
NODE_ENV = "production"
REACT_APP_API_URL = "https://sodav-monitor-production.up.railway.app"
REACT_APP_WS_URL = "wss://sodav-monitor-production.up.railway.app/ws"
AUDIO_PROCESSING_ENABLED = "true"
AUDIO_PROCESSING_INTERVAL = "30"
AUDIO_PROCESSING_DURATION = "10"
AUDIO_PROCESSING_TIMEOUT = "30"
AUDIO_PROCESSING_RETRIES = "3"
AUDIO_PROCESSING_RETRY_DELAY = "5"
REQUEST_TIMEOUT = 10
CHUNK_SIZE = 8192
MAX_RETRIES = 3
MIN_AUDIO_LENGTH = 10
MAX_AUDIO_LENGTH = 30
SAMPLE_RATE = 44100
CHANNELS = 2
MIN_CONFIDENCE = 50
MIN_RHYTHM_STRENGTH = 30
MIN_BASS_ENERGY = 20
MIN_MID_ENERGY = 15 