"""Initial migration

Revision ID: 3ca146e9a158
Revises: combined_migration
Create Date: 2025-02-16 03:25:07.078294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca146e9a158'
down_revision: Union[str, None] = 'combined_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_stations', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('active', 'inactive', name='stationstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_stations', 'status',
               existing_type=sa.Enum('active', 'inactive', name='stationstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###
