"""Initial migration

Revision ID: 0f10f1b9f1cf
Revises: 
Create Date: 2025-02-18 15:35:08.425734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0f10f1b9f1cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    stationstatus = postgresql.ENUM('active', 'inactive', name='stationstatus')
    stationstatus.create(op.get_bind())
    
    # Then alter the column with explicit USING clause
    op.execute('ALTER TABLE radio_stations ALTER COLUMN status TYPE stationstatus USING status::stationstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_stations', 'status',
               existing_type=sa.Enum('active', 'inactive', name='stationstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    
    # Drop the enum type
    stationstatus = postgresql.ENUM('active', 'inactive', name='stationstatus')
    stationstatus.drop(op.get_bind())
    # ### end Alembic commands ###
