name: E2E Tests Local

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-all-tests]
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight
  push:
    paths:
      - 'backend/**'
      - 'tests/e2e/**'
      - 'requirements.txt'
      - '.github/workflows/e2e_tests_local.yml'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sodav_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Create directories for test results
        run: |
          mkdir -p test-results coverage-reports

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio pre-commit

      - name: Run pre-commit hooks
        run: |
          pre-commit install
          pre-commit run --all-files || echo "Pre-commit hooks completed with warnings"

      - name: Run E2E tests
        run: |
          python -m pytest tests/e2e/ -v

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            coverage-reports/
