name: Feature Extractor Tests

on:
  push:
    paths:
      - 'backend/detection/audio_processor/feature_extractor.py'
      - 'backend/tests/**/test_feature_extractor.py'
      - '.github/workflows/feature_extractor_tests.yml'
  pull_request:
    paths:
      - 'backend/detection/audio_processor/feature_extractor.py'
      - 'backend/tests/**/test_feature_extractor.py'
  repository_dispatch:
    types: [run-all-tests]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-feature-extractor:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sodav_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1 ffmpeg

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio pre-commit

      - name: Create directories for test results
        run: |
          mkdir -p test-results coverage-reports

      - name: Run pre-commit hooks (non-blocking)
        run: |
          pre-commit install
          pre-commit run --all-files || {
            echo "::warning::Pre-commit hooks found issues, but continuing with tests"
            echo "Pre-commit issues found. These should be fixed in future commits."
          }
        continue-on-error: true

      - name: Run feature extractor tests
        run: |
          python -m pytest backend/tests/unit/detection/audio_processor/test_feature_extractor.py -v --cov=backend.detection.audio_processor.feature_extractor --cov-report=xml:coverage-reports/coverage.xml
        env:
          PYTHONPATH: .
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/sodav_dev
          REDIS_URL: redis://localhost:6379/0
          API_V1_STR: /api/v1
          SECRET_KEY: test_secret_key
          ACOUSTID_API_KEY: test_acoustid_key
          AUDD_API_KEY: test_audd_key

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: feature-extractor-test-results
          path: |
            test-results/
            coverage-reports/ 